FROM ubuntu:groovy

VOLUME ["/pkg"]

RUN apt-get --assume-yes update
RUN DEBIAN_FRONTEND=noninteractive apt-get --assume-yes upgrade
RUN DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install build-essential reprepro rsync wget zip git 

ENTRYPOINT ["makepkg"]
